### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Pool800** [DDDASHXD/zoombrute#3]
So zoom updated the way their meeting joining system works so this does not work anymore.

**Comment by ilanlansh** [comment]
is this going to be updated?

**Comment by zer0mania** [comment]
https://github.com/zer0mania/zoom-scraper updated and uses requests

**Comment by DDDASHXD** [comment]
> 
Readme updated (:
https://github.com/DDDASHXD/ZoomBrute.py/commit/528db927542b19d7242c0a15fa68e13aaa233ea6
